# Generated by Django 5.0.2 on 2024-02-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_moderation_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exception',
            new_name='ExceptionWord',
        ),
    ]
