# Generated by Django 5.0.2 on 2024-02-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_moderation_system', '0004_rename_date_time_of_review_review_review_created_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='middle_name',
            field=models.CharField(default='Uknown', max_length=100, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
