# Generated by Django 5.0.2 on 2024-02-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_moderation_system', '0005_remove_doctor_name_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='processed_review',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Обработанный отзыв'),
        ),
    ]
